[package]
name = "nutrino"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proto = { git = "https://github.com/Dhhoyt/Proto.git" }
eframe = "0.22.0"
egui_node_graph = "0.4.0"